name: OneCart CI/CD pipeline
on: push

jobs:
  WORKSPACE_CLEANUP:
    runs-on: self-hosted
    steps: 
      - name: workspace cleanup
        run: |
          rm -rf ./* ./.??* || true  

  CODE_CHECKOUT:
    needs: WORKSPACE_CLEANUP
    runs-on: self-hosted
    steps:
      - name: code checkout
        uses: actions/checkout@v4

  NPM_SETUP:
    needs: CODE_CHECKOUT
    runs-on: self-hosted
    steps:
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Verify Workspace
        run: |
          pwd
          ls -la  

      - name: Check Node and npm
        run: |
          node -v
          npm -v      

      - name: NPM Install
        run: npm ci  

      - name: NPM test
        run: npm test   
      

      - name: Create Artifact Directory
        run: |
          mkdir -p build-artifacts/onecart-artifact



      - name: Create Zip file 
        run: |
           zip -r build-artifacts/onecart-artifact/onecart-${{ github.run_number }}.zip \
           server.js \
           views \
           public \
           package.json \
           package-lock.json \
           Dockerfile  
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifacts/onecart-artifact/onecart-${{ github.run_number }}.zip
  
  NEXUS_REPOSITORY_PUSH:
    needs: NPM_SETUP
    runs-on: self-hosted
    steps:
      - name: downlaoding the artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: uplaod .zip file to nexus repo  
        run: | 
          curl -u "${{secrets.NEXUS_USERNAME}}:${{secrets.NEXUS_PASSWORD}}" \
          --upload-file build-artifacts/onecart-artifact/onecart-${{ github.run_number }}.zip \
          "http://40.192.118.179:8081/repository/build-artifacts/onecart-artifact/onecart-${{ github.run_number }}.zip"
 
 
  SONARQUBE_SCAN:
    needs: NEXUS_REPOSITORY_PUSH
    runs-on: self-hosted
    steps:
      - name: SonarQube Scan
        run: |
          docker run --rm \
          -e SONAR_HOST_URL="${{ secrets.SONARQUBE_SERVER }}" \
          -e SONAR_TOKEN="${{ secrets.SONARQUBE_TOKEN }}" \
          -v "${{ github.workspace }}:/usr/src" \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=onecart-web-application \
          -Dsonar.projectName=onecart-web-application \
          -Dsonar.sources=/usr/src
      # - name: sonarqube analysis
      #   run: |
      #     ls -l /opt/sonar-scanner/bin
      #     /opt/sonar-scanner/bin/sonar-scanner \
      #     -Dsonar.projectKey=onecart-web-application \
      #     -Dsonar.projectName=onecart-web-application \
      #     -Dsonar.sources=. \
      #     -Dsonar.host.url=${{ secrets.SONARQUBE_SERVER }} \
      #     -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}    
 
 
  DOCKER_BUILD:
    needs: SONARQUBE_SCAN
    runs-on: self-hosted
    steps:
      - name: Image Build
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/onecart-image:${{github.run_number}} .

      - name: docker images list
        run: docker images

  TRIVY_SCAN:
    needs: DOCKER_BUILD
    runs-on: self-hosted
    steps:
      - name: Trivy Scan
        run: |
          trivy image \
          --format table \
          --template "@contrib/html.tpl" \
          -o trivy-report.html \
          ${{secrets.DOCKER_USERNAME}}/onecart-image:${{ github.run_number }}   
  
  DOCKER_PUSH:
    needs: TRIVY_SCAN
    runs-on: self-hosted
    steps: 
      - name: Docker login 
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker push
        run: |
         docker push ${{secrets.DOCKER_USERNAME}}/onecart-image:${{github.run_number}}    

  ECR_PUSH:
    needs: DOCKER_PUSH 
    runs-on: self-hosted
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
          aws-region: ap-south-1   
      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag DOCKER Image to ECR 
        run: |
          docker tag \
          ${{secrets.DOCKER_USERNAME}}/onecart-image:${{ github.run_number }} \
          ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.ap-south-2.amazonaws.com/onecart-images:${{ github.run_number }}

      - name: Push Docker Image to ECR
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-2.amazonaws.com/onecart-image:${{ github.run_number }}

      